name: NÃ©stor Espinoza, Astrophysicist.
description: Personal website.
url: https://www.nestor-espinoza.com
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
language: en
disqus: nestor-espinoza
default_image: /images/modern-web.jpg
